
package hotel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Employee extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    private String userid="";
    public Employee() {
        initComponents();
    }
    public Employee(String tempuserid) throws SQLException {
        try {
            initComponents();
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","$1Anuradha");
            userid=tempuserid;
            setLocationRelativeTo(null);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlabel9 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        jemp = new javax.swing.JTextField();
        jename = new javax.swing.JTextField();
        jjob = new javax.swing.JTextField();
        jgender = new javax.swing.JTextField();
        insert_button1 = new java.awt.Button();
        delete_button1 = new java.awt.Button();
        update_button1 = new java.awt.Button();
        search_button1 = new java.awt.Button();
        back_button1 = new java.awt.Button();
        jlabel5 = new javax.swing.JLabel();
        jphone = new javax.swing.JTextField();
        jlabel6 = new javax.swing.JLabel();
        jmgrid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jsalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jphone3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jlabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/all pages background.png"))); // NOI18N
        jlabel8.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("EMPLOYEE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 38, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("EMPID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 123, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ENAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 180, -1, -1));

        jlabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel9.setText("JOB_DESC");
        jPanel1.add(jlabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 243, -1, -1));

        jlabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel4.setText("GENDER");
        jPanel1.add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 299, 57, -1));
        jPanel1.add(jemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 121, 314, -1));

        jename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenameActionPerformed(evt);
            }
        });
        jPanel1.add(jename, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 178, 314, -1));
        jPanel1.add(jjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 241, 310, -1));
        jPanel1.add(jgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 297, 310, -1));

        insert_button1.setBackground(new java.awt.Color(204, 204, 255));
        insert_button1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        insert_button1.setLabel("INSERT");
        insert_button1.setName(""); // NOI18N
        insert_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_button1ActionPerformed(evt);
            }
        });
        jPanel1.add(insert_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));

        delete_button1.setBackground(new java.awt.Color(204, 204, 255));
        delete_button1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        delete_button1.setLabel("DELETE");
        delete_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_button1ActionPerformed(evt);
            }
        });
        jPanel1.add(delete_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        update_button1.setBackground(new java.awt.Color(204, 204, 255));
        update_button1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        update_button1.setLabel("UPDATE");
        update_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_button1ActionPerformed(evt);
            }
        });
        jPanel1.add(update_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, -1, -1));

        search_button1.setBackground(new java.awt.Color(204, 204, 255));
        search_button1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        search_button1.setLabel("SEARCH");
        search_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_button1ActionPerformed(evt);
            }
        });
        jPanel1.add(search_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, -1, -1));

        back_button1.setBackground(new java.awt.Color(204, 204, 255));
        back_button1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        back_button1.setLabel("BACK");
        back_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_button1ActionPerformed(evt);
            }
        });
        jPanel1.add(back_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, -1, -1));

        jlabel5.setText("PHONE");
        jPanel1.add(jlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));
        jPanel1.add(jphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 310, -1));

        jlabel6.setText("MGRID");
        jPanel1.add(jlabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 403, -1, -1));
        jPanel1.add(jmgrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 400, 310, -1));

        jLabel4.setText("SALARY");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 452, -1, -1));
        jPanel1.add(jsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 448, 310, -1));

        jLabel5.setText("PHONE2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));
        jPanel1.add(jphone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 320, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/all pages background.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenameActionPerformed

    private void insert_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_button1ActionPerformed
        try {

            String e1=jemp.getText();
            String n1=jename.getText();
            String j1=jjob.getText();
            String g1=jgender.getText();
            String m1=jmgrid.getText();
            String s1=jsalary.getText();
            String p1=jphone.getText();
            String ph1=jphone3.getText();
            pst=con.prepareStatement("INSERT INTO EMPLOYEE VALUES('"+e1+"','"+n1+"','"+j1+"','"+g1+"','"+m1+"','"+s1+"')");
            pst.executeUpdate();
            pst=con.prepareStatement("INSERT INTO EMP_PHONE VALUES('"+e1+"','"+p1+"','"+ph1+"')");
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Inserted");
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_insert_button1ActionPerformed

    private void delete_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button1ActionPerformed
        try {
            // TODO add your handling code here:
            String e2=JOptionPane.showInputDialog(this,"Enter employee id to delete:");
            int flag=0;
            pst=con.prepareStatement("SELECT * FROM EMPLOYEE WHERE EMPID='"+e2+"'");
            rs=pst.executeQuery();
            while(rs.next()){
                String c=rs.getString("EMPID");
                if(e2.equals(c))
                {
                    flag=1;
                    pst=con.prepareStatement("DELETE FROM EMPLOYEE WHERE EMPID='"+e2+"'");
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Deleted");
                }
            }
            if(flag==0){
                JOptionPane.showMessageDialog(this,"No record found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_button1ActionPerformed

    private void update_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_button1ActionPerformed
        try {
            // TODO add your handling code here:
            String e3=JOptionPane.showInputDialog(this,"Enter employee id to update salary:");
            int flag=0;
            pst=con.prepareStatement("SELECT * FROM EMPLOYEE WHERE EMPID='"+e3+"'");
            rs=pst.executeQuery();
            while(rs.next())
            {
                String e=rs.getString("EMPID");
                if(e3.equals(e))
                {
                    flag=1;
                    String s2=JOptionPane.showInputDialog(this,"Enter salary:");
                    pst=con.prepareStatement("UPDATE EMPLOYEE SET SALARY='"+s2+"'WHERE EMPID='"+e3+"'");
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Updated");
                }
            }
            if(flag==0){
                JOptionPane.showMessageDialog(this,"No record found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_button1ActionPerformed

    private void search_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_button1ActionPerformed
        try {
            // TODO add your handling code here:
            String e4=JOptionPane.showInputDialog(this,"Enter employee id to search:");
            pst=con.prepareStatement("SELECT * FROM EMPLOYEE WHERE EMPID='"+e4+"'");
            rs=pst.executeQuery();
            int flag=0;
            while(rs.next())
            {
                String e=rs.getString("EMPID");
                if(e4.equals(e))
                {
                    flag=1;
                    jemp.setText(rs.getString("EMPID"));
                    jename.setText(rs.getString("ENAME"));
                    jjob.setText(rs.getString("JOB_DESC"));
                    jgender.setText(rs.getString("GENDER"));
                    jmgrid.setText(rs.getString("MGR_ID"));
                    jsalary.setText(rs.getString("SALARY"));  
                }
            }
            pst=con.prepareStatement("SELECT * FROM EMP_PHONE WHERE EMPID='"+e4+"'");
            rs=pst.executeQuery();
            while(rs.next())
            {
                flag=1;
                jphone.setText(rs.getString("PHONE"));
            }
            if(flag==0)
            {
                JOptionPane.showMessageDialog(this,"No record found");
            }
        }
        
        
        catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_search_button1ActionPerformed

    private void back_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_button1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Dashboard d=new Dashboard();
        d.setVisible(true);
    }//GEN-LAST:event_back_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button back_button1;
    private java.awt.Button delete_button1;
    private java.awt.Button insert_button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jemp;
    private javax.swing.JTextField jename;
    private javax.swing.JTextField jgender;
    private javax.swing.JTextField jjob;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel jlabel9;
    private javax.swing.JTextField jmgrid;
    private javax.swing.JTextField jphone;
    private javax.swing.JTextField jphone3;
    private javax.swing.JTextField jsalary;
    private java.awt.Button search_button1;
    private java.awt.Button update_button1;
    // End of variables declaration//GEN-END:variables
}
